---
title: Premiers pas dans ma nouvelle vie...
author: Laurent
date: '2018-10-17'
slug: this-site-in-under-construction
categories:
  - General
tags: 
description: ''
featured_image: ''
---


```{r, eval=TRUE, echo = F}
blogdown::shortcode("youtube", "LA7T0GSjzg0")
```

Voilà... Les rails qui guidaient mes pas se sont brutalement arrêtés... Pas si brutalement en fait... Mais bon, maintenant c'est fait. Je veux éviter de revenir trop sur la passé. Pour l'instant, ce qui compte c'est de regarder devant... Peut-être y aura-t'il plus tard d'autres articles de blogs sur les circonstances qui m'ont amené ici, mais pas maintenant.

Il va falloir que j'écrive les pages de cette nouvelle vie, et c'est assez nouveau pour moi: je n'ai pas de template! Je suis devant une page blanche (ou presque). C'est excitant... et intimidant, si je l'avoue.

En Janvier, je vais commencer mon programme de M.Sc. à HEC... Ça aussi c'est exaltant et intimidant. Je regardais hier les plans des cours obligatoires, et j'avais une petite voix en moi qui me disait "Oh my god! dans quoi tu t'es embarqué?". En tout cas, s'il était vital pour moi que je sorte de ma zone de confort, il semble que ca va être le cas!

Le programme pour les prochaines semaines d'ici la rentrée est assez lâche. Il y a bien sur nos 4 jours à Manhattan pour la semaine de thanksgiving. Mais pour l'instant, j'égrène mes journées à continuer à m'auto-former.

Et comme le dit Zazie dans sa chanson, je suis "flambant vieux!"



